"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
router.get('', getUser);
router.get('/:id', getAllUser);
router.post('', addUser);
router.put('/:id', updateUser);
router.delete('/:id', deleteUser);
exports.default = router;
